// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEj-WqYw8v6Y_PjSmwR5yM0Pz-raEchTo',
    appId: '1:595479399306:web:26176ba9d54e9dcc631673',
    messagingSenderId: '595479399306',
    projectId: 'quizapp-a5ea5',
    authDomain: 'quizapp-a5ea5.firebaseapp.com',
    storageBucket: 'quizapp-a5ea5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFo8iw7EyzGzUc-KOxxMZP26x5A7hD6o',
    appId: '1:595479399306:android:6a02645ac09a50e5631673',
    messagingSenderId: '595479399306',
    projectId: 'quizapp-a5ea5',
    storageBucket: 'quizapp-a5ea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjNR68AZ2JW8D4Y5AcUGA0ReFAiZk787g',
    appId: '1:595479399306:ios:d0fc8a6f05e3dc0c631673',
    messagingSenderId: '595479399306',
    projectId: 'quizapp-a5ea5',
    storageBucket: 'quizapp-a5ea5.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjNR68AZ2JW8D4Y5AcUGA0ReFAiZk787g',
    appId: '1:595479399306:ios:d0fc8a6f05e3dc0c631673',
    messagingSenderId: '595479399306',
    projectId: 'quizapp-a5ea5',
    storageBucket: 'quizapp-a5ea5.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEj-WqYw8v6Y_PjSmwR5yM0Pz-raEchTo',
    appId: '1:595479399306:web:13cd0acce5036898631673',
    messagingSenderId: '595479399306',
    projectId: 'quizapp-a5ea5',
    authDomain: 'quizapp-a5ea5.firebaseapp.com',
    storageBucket: 'quizapp-a5ea5.firebasestorage.app',
  );
}
